version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./upload:/var/www/html/upload
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_USER=bf_shop_user
      - DB_PASS=bf_shop_password
      - DB_NAME=bf_shop

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=bf_shop
      - MYSQL_USER=bf_shop_user
      - MYSQL_PASSWORD=bf_shop_password

volumes:
  mysql_data:
